//! Data-driven Islamic ontology seed integration for Phase 3.
//!
//! The generic ontology model remains domain-agnostic. This module only
//! translates the small, data-driven Islamic seed vocabulary into the generic
//! [`Ontology`] structures. Class identities are generated by Core at load
//! time; seed keys are stable data keys and are never treated as identities.
//!
//! The seed intentionally contains only structural vocabulary and taxonomy.
//! Evidence, provenance, authority, inference, persistence, and ontology
//! version management remain outside this Phase 3 integration boundary.

use core::fmt;
use std::collections::BTreeMap;

use serde_json::Value;

use super::{Class, ClassId, Ontology, OntologyError};

/// Embedded path of the initial Islamic ontology seed.
const ISLAMIC_SEED_DATA: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/data/ontology/islamic_seed.json"
));

/// The loaded data-driven Islamic ontology seed.
///
/// The seed owns the resulting generic ontology plus the mapping from stable
/// data keys to Core-generated [`ClassId`] values. The mapping is intentionally
/// kept outside the JSON data so the seed cannot prescribe canonical
/// identities.
#[derive(Clone, Debug)]
pub struct IslamicSeed {
    name: String,
    ontology: Ontology,
    class_ids: BTreeMap<String, ClassId>,
}

impl IslamicSeed {
    /// Returns the seed's descriptive name.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Returns the generic ontology produced from the seed.
    #[must_use]
    pub fn ontology(&self) -> &Ontology {
        &self.ontology
    }

    /// Returns the Core-generated class identity for a seed key.
    #[must_use]
    pub fn class_id(&self, key: &str) -> Option<&ClassId> {
        self.class_ids.get(key)
    }

    /// Returns all seed-key/class-identity pairs in deterministic key order.
    pub fn class_ids(&self) -> impl Iterator<Item = (&str, &ClassId)> {
        self.class_ids.iter().map(|(key, id)| (key.as_str(), id))
    }

    /// Consumes the loaded seed and returns its generic ontology.
    #[must_use]
    pub fn into_ontology(self) -> Ontology {
        self.ontology
    }
}

/// Loads the embedded Islamic ontology seed.
///
/// The JSON file is compiled into the crate as data. Every class receives a
/// fresh Core-generated [`ClassId`] while the JSON keys are used only to wire
/// taxonomy references during loading.
pub fn load_islamic_seed() -> Result<IslamicSeed, IslamicSeedError> {
    load_islamic_seed_from_str(ISLAMIC_SEED_DATA)
}

/// Loads an Islamic ontology seed from JSON text.
///
/// This lower-level entry point is useful for tests and future tooling that may
/// provide another validated seed source without changing the generic ontology
/// model.
pub fn load_islamic_seed_from_str(input: &str) -> Result<IslamicSeed, IslamicSeedError> {
    let root: Value = serde_json::from_str(input).map_err(IslamicSeedError::Json)?;
    let object = root.as_object().ok_or(IslamicSeedError::RootMustBeObject)?;

    let name = required_non_empty_string(object, "name")?.to_owned();
    let classes = object
        .get("classes")
        .and_then(Value::as_array)
        .ok_or(IslamicSeedError::MissingOrInvalidField { field: "classes" })?;
    let taxonomy = object
        .get("taxonomy")
        .and_then(Value::as_array)
        .ok_or(IslamicSeedError::MissingOrInvalidField { field: "taxonomy" })?;

    let mut ontology = Ontology::new();
    let mut class_ids = BTreeMap::new();

    for (index, class_definition) in classes.iter().enumerate() {
        let class_object = class_definition
            .as_object()
            .ok_or(IslamicSeedError::InvalidClassDefinition { index })?;

        let key = required_non_empty_string(class_object, "key")?.to_owned();
        let label = required_non_empty_string(class_object, "label")?.to_owned();

        if class_ids.contains_key(&key) {
            return Err(IslamicSeedError::DuplicateClassKey { key });
        }

        let class_id = ClassId::generate();
        ontology
            .add_class(Class::new(class_id.clone(), label))
            .map_err(IslamicSeedError::Ontology)?;

        class_ids.insert(key, class_id);
    }

    for (index, relation) in taxonomy.iter().enumerate() {
        let relation_object = relation
            .as_object()
            .ok_or(IslamicSeedError::InvalidTaxonomyDefinition { index })?;

        let child_key = required_non_empty_string(relation_object, "child")?;
        let parent_key = required_non_empty_string(relation_object, "parent")?;

        let child =
            class_ids
                .get(child_key)
                .cloned()
                .ok_or_else(|| IslamicSeedError::UnknownClassKey {
                    key: child_key.to_owned(),
                })?;
        let parent = class_ids.get(parent_key).cloned().ok_or_else(|| {
            IslamicSeedError::UnknownClassKey {
                key: parent_key.to_owned(),
            }
        })?;

        ontology
            .add_class_parent(child, parent)
            .map_err(IslamicSeedError::Ontology)?;
    }

    Ok(IslamicSeed {
        name,
        ontology,
        class_ids,
    })
}

fn required_non_empty_string<'a>(
    object: &'a serde_json::Map<String, Value>,
    field: &'static str,
) -> Result<&'a str, IslamicSeedError> {
    object
        .get(field)
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty())
        .ok_or(IslamicSeedError::MissingOrInvalidField { field })
}

/// Errors produced while loading the data-driven Islamic seed.
#[derive(Debug)]
pub enum IslamicSeedError {
    /// The seed could not be decoded as JSON.
    Json(serde_json::Error),

    /// The JSON root must be an object.
    RootMustBeObject,

    /// A required field is missing, not a string, not an array, or empty.
    MissingOrInvalidField {
        /// Name of the invalid field.
        field: &'static str,
    },

    /// A class entry is not a JSON object.
    InvalidClassDefinition {
        /// Zero-based class entry index.
        index: usize,
    },

    /// A taxonomy entry is not a JSON object.
    InvalidTaxonomyDefinition {
        /// Zero-based taxonomy entry index.
        index: usize,
    },

    /// Two class definitions use the same stable seed key.
    DuplicateClassKey {
        /// Duplicated seed key.
        key: String,
    },

    /// A taxonomy relation references a class key that was not defined.
    UnknownClassKey {
        /// Unknown seed key.
        key: String,
    },

    /// The generic ontology rejected the seed structure.
    Ontology(OntologyError),
}

impl fmt::Display for IslamicSeedError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Json(error) => write!(formatter, "invalid Islamic ontology seed JSON: {error}"),
            Self::RootMustBeObject => {
                write!(formatter, "Islamic ontology seed root must be an object")
            }
            Self::MissingOrInvalidField { field } => {
                write!(
                    formatter,
                    "Islamic ontology seed field '{field}' is missing or invalid"
                )
            }
            Self::InvalidClassDefinition { index } => {
                write!(
                    formatter,
                    "Islamic ontology seed class at index {index} must be an object"
                )
            }
            Self::InvalidTaxonomyDefinition { index } => {
                write!(
                    formatter,
                    "Islamic ontology seed taxonomy entry at index {index} must be an object"
                )
            }
            Self::DuplicateClassKey { key } => {
                write!(
                    formatter,
                    "Islamic ontology seed contains duplicate class key: {key}"
                )
            }
            Self::UnknownClassKey { key } => {
                write!(
                    formatter,
                    "Islamic ontology seed references unknown class key: {key}"
                )
            }
            Self::Ontology(error) => write!(
                formatter,
                "Islamic ontology seed violates ontology structure: {error}"
            ),
        }
    }
}

impl std::error::Error for IslamicSeedError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Json(error) => Some(error),
            Self::Ontology(error) => Some(error),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{IslamicSeedError, load_islamic_seed, load_islamic_seed_from_str};

    #[test]
    fn embedded_seed_loads_into_generic_ontology() {
        let seed = load_islamic_seed().expect("embedded Islamic seed should load");

        assert_eq!(seed.name(), "islamic-core");
        assert_eq!(seed.ontology().class_count(), 10);
        assert_eq!(seed.ontology().class_taxonomy().len(), 10);
    }

    #[test]
    fn seed_keys_resolve_to_core_generated_class_identities() {
        let seed = load_islamic_seed().expect("embedded Islamic seed should load");

        let person = seed.class_id("person").expect("person key should exist");
        let prophet = seed.class_id("prophet").expect("prophet key should exist");

        assert_ne!(person, prophet);
        assert!(!person.as_str().is_empty());
        assert!(!prophet.as_str().is_empty());
    }

    #[test]
    fn seed_taxonomy_uses_generated_class_identities() {
        let seed = load_islamic_seed().expect("embedded Islamic seed should load");
        let prophet = seed.class_id("prophet").expect("prophet key should exist");
        let person = seed.class_id("person").expect("person key should exist");

        let parents = seed
            .ontology()
            .class_taxonomy()
            .parents_of(prophet)
            .expect("prophet should be a taxonomy node");

        assert!(parents.contains(person));
    }

    #[test]
    fn duplicate_class_keys_are_rejected() {
        let input = r#"
        {
          "name": "test",
          "classes": [
            {"key": "person", "label": "Person"},
            {"key": "person", "label": "Duplicate"}
          ],
          "taxonomy": []
        }
        "#;

        assert!(matches!(
            load_islamic_seed_from_str(input),
            Err(IslamicSeedError::DuplicateClassKey { .. })
        ));
    }

    #[test]
    fn unknown_taxonomy_class_keys_are_rejected() {
        let input = r#"
        {
          "name": "test",
          "classes": [
            {"key": "person", "label": "Person"}
          ],
          "taxonomy": [
            {"child": "prophet", "parent": "person"}
          ]
        }
        "#;

        assert!(matches!(
            load_islamic_seed_from_str(input),
            Err(IslamicSeedError::UnknownClassKey { .. })
        ));
    }

    #[test]
    fn malformed_json_is_rejected() {
        assert!(matches!(
            load_islamic_seed_from_str("{not-json}"),
            Err(IslamicSeedError::Json(_))
        ));
    }
}
